import JSZip from "jszip";
import { extractPlainText, replaceTextAcrossRuns, setRunsText, findBlockRanges } from "./xmlTextUtil.js";

interface SlideRef {
  rId: string;
  target: string; // e.g. "slides/slide3.xml"
  path: string; // e.g. "ppt/slides/slide3.xml"
}

async function getRelTargets(zip: JSZip, relsPath: string): Promise<Map<string, string>> {
  const xml = await zip.file(relsPath)?.async("string");
  const map = new Map<string, string>();
  if (!xml) return map;
  const re = /<Relationship[^>]*Id="([^"]+)"[^>]*Target="([^"]+)"/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(xml))) map.set(m[1], m[2]);
  return map;
}

async function getSlideOrder(zip: JSZip): Promise<SlideRef[]> {
  const presXml = await zip.file("ppt/presentation.xml")?.async("string");
  if (!presXml) throw new Error("Не удалось прочитать ppt/presentation.xml");
  const relTargets = await getRelTargets(zip, "ppt/_rels/presentation.xml.rels");

  const sldIdRe = /<p:sldId[^>]*r:id="([^"]+)"[^>]*\/>/g;
  const refs: SlideRef[] = [];
  let m: RegExpExecArray | null;
  while ((m = sldIdRe.exec(presXml))) {
    const rId = m[1];
    const target = relTargets.get(rId);
    if (!target) continue;
    refs.push({ rId, target, path: `ppt/${target.replace(/^\.?\//, "")}` });
  }
  return refs;
}

interface ShapeBlock {
  start: number;
  end: number;
  isTitle: boolean;
  isPlaceholder: boolean;
}

function findShapeBlocks(xml: string): ShapeBlock[] {
  const spRe = /<p:sp>[\s\S]*?<\/p:sp>/g;
  const blocks: ShapeBlock[] = [];
  let m: RegExpExecArray | null;
  while ((m = spRe.exec(xml))) {
    const block = m[0];
    const isPlaceholder = /<p:ph\b/.test(block);
    const isTitle = /<p:ph\b[^>]*type="(ctrTitle|title)"/.test(block);
    blocks.push({ start: m.index, end: m.index + block.length, isTitle, isPlaceholder });
  }
  return blocks;
}

// Slides authored in real PowerPoint templates use <p:ph type="title"/> and a
// body placeholder — detected directly. Slides generated by pptxgenjs (our
// own create_file_from_description tool) use plain text boxes with no
// placeholder markup at all, so we fall back to positional shapes (1st textbox
// = title, 2nd = body) rather than silently finding nothing to edit.
function pickTitleAndBodyBlocks(blocks: ShapeBlock[]): { titleBlock?: ShapeBlock; bodyBlock?: ShapeBlock } {
  let titleBlock = blocks.find((b) => b.isTitle);
  let bodyBlock = blocks.find((b) => b.isPlaceholder && !b.isTitle);
  if (!titleBlock && blocks.length > 0) titleBlock = blocks[0];
  if (!bodyBlock) bodyBlock = blocks.find((b) => b !== titleBlock);
  return { titleBlock, bodyBlock };
}

export interface SlideSummary {
  index: number;
  title: string;
  text: string;
}

export async function listSlides(buffer: Buffer): Promise<SlideSummary[]> {
  const zip = await JSZip.loadAsync(buffer);
  const order = await getSlideOrder(zip);
  const summaries: SlideSummary[] = [];
  for (let i = 0; i < order.length; i++) {
    const xml = await zip.file(order[i].path)?.async("string");
    if (!xml) continue;
    const blocks = findShapeBlocks(xml);
    const { titleBlock } = pickTitleAndBodyBlocks(blocks);
    const title = titleBlock ? extractPlainText(xml.slice(titleBlock.start, titleBlock.end), "a:t") : "";
    const fullText = extractPlainText(xml, "a:t", " ");
    summaries.push({ index: i, title, text: fullText });
  }
  return summaries;
}

export async function editSlideText(buffer: Buffer, slideIndex: number, find: string, replace: string): Promise<{ buffer: Buffer; occurrences: number }> {
  const zip = await JSZip.loadAsync(buffer);
  const order = await getSlideOrder(zip);
  const ref = order[slideIndex];
  if (!ref) throw new Error(`Слайд с индексом ${slideIndex} не существует`);
  let xml = await zip.file(ref.path)?.async("string");
  if (!xml) throw new Error("Не удалось прочитать слайд");

  // Scoped per-paragraph, nested within each shape (never slide-wide): a
  // slide-wide flatten/redistribute would merge text across unrelated shapes
  // (e.g. the title box and the bullet list) into a single run, and even a
  // shape-wide one would merge separate bullet paragraphs together, losing
  // the line breaks between them. Each paragraph's own runs are still
  // flattened together so a phrase split across runs within one paragraph
  // (the common Word/PowerPoint run-fragmentation case) is still matched.
  const shapeBlocks = findShapeBlocks(xml);
  let totalOccurrences = 0;
  for (let s = shapeBlocks.length - 1; s >= 0; s--) {
    const shape = shapeBlocks[s];
    let shapeXml: string = xml.slice(shape.start, shape.end);
    const paraBlocks = findBlockRanges(shapeXml, "a:p");
    let shapeChanged = false;
    for (let p = paraBlocks.length - 1; p >= 0; p--) {
      const para = paraBlocks[p];
      const fragment = shapeXml.slice(para.start, para.end);
      const result = replaceTextAcrossRuns(fragment, "a:t", find, replace);
      if (result.changed) {
        totalOccurrences += result.occurrences;
        shapeChanged = true;
        shapeXml = shapeXml.slice(0, para.start) + result.xml + shapeXml.slice(para.end);
      }
    }
    if (shapeChanged) xml = xml.slice(0, shape.start) + shapeXml + xml.slice(shape.end);
  }
  if (totalOccurrences === 0) return { buffer, occurrences: 0 };

  zip.file(ref.path, xml);
  const out = await zip.generateAsync({ type: "nodebuffer" });
  return { buffer: out, occurrences: totalOccurrences };
}

export async function setSlideTitleAndBody(buffer: Buffer, slideIndex: number, title?: string, body?: string): Promise<Buffer> {
  const zip = await JSZip.loadAsync(buffer);
  const order = await getSlideOrder(zip);
  const ref = order[slideIndex];
  if (!ref) throw new Error(`Слайд с индексом ${slideIndex} не существует`);
  let xml = await zip.file(ref.path)?.async("string");
  if (!xml) throw new Error("Не удалось прочитать слайд");

  const blocks = findShapeBlocks(xml);
  const { titleBlock, bodyBlock } = pickTitleAndBodyBlocks(blocks);

  // Apply from the later block first so earlier offsets stay valid.
  const edits: { block: { start: number; end: number }; text: string }[] = [];
  if (title !== undefined && titleBlock) edits.push({ block: titleBlock, text: title });
  if (body !== undefined && bodyBlock) edits.push({ block: bodyBlock, text: body });
  edits.sort((a, b) => b.block.start - a.block.start);

  for (const edit of edits) {
    const fragment = xml.slice(edit.block.start, edit.block.end);
    const newFragment = setRunsText(fragment, "a:t", edit.text);
    xml = xml.slice(0, edit.block.start) + newFragment + xml.slice(edit.block.end);
  }

  zip.file(ref.path, xml);
  return zip.generateAsync({ type: "nodebuffer" });
}

export async function addSlide(buffer: Buffer, afterIndex: number, title: string, body: string): Promise<Buffer> {
  const zip = await JSZip.loadAsync(buffer);
  const order = await getSlideOrder(zip);
  const templateRef = order[order.length - 1] ?? order[0];
  if (!templateRef) throw new Error("В презентации нет слайдов, на основе которых можно создать новый");

  const templateXml = await zip.file(templateRef.path)?.async("string");
  if (!templateXml) throw new Error("Не удалось прочитать слайд-шаблон");

  // Find next free slide number and content-types-safe filename.
  const existingNumbers = Object.keys(zip.files)
    .map((name) => /^ppt\/slides\/slide(\d+)\.xml$/.exec(name)?.[1])
    .filter((n): n is string => !!n)
    .map(Number);
  const nextNum = Math.max(0, ...existingNumbers) + 1;
  const newSlidePath = `ppt/slides/slide${nextNum}.xml`;
  const newRelsPath = `ppt/slides/_rels/slide${nextNum}.xml.rels`;

  // Clone the template slide's own relationships (usually just its layout).
  const templateRelsPath = `ppt/slides/_rels/${templateRef.target.split("/").pop()}.rels`;
  const templateRels = await zip.file(templateRelsPath)?.async("string");
  if (templateRels) zip.file(newRelsPath, templateRels);

  // Overwrite the cloned slide's title/body placeholder text.
  const blocks = findShapeBlocks(templateXml);
  let newXml = templateXml;
  const { titleBlock, bodyBlock } = pickTitleAndBodyBlocks(blocks);
  const edits: { block: { start: number; end: number }; text: string }[] = [];
  if (titleBlock) edits.push({ block: titleBlock, text: title });
  if (bodyBlock) edits.push({ block: bodyBlock, text: body });
  edits.sort((a, b) => b.block.start - a.block.start);
  for (const edit of edits) {
    const fragment = newXml.slice(edit.block.start, edit.block.end);
    const newFragment = setRunsText(fragment, "a:t", edit.text);
    newXml = newXml.slice(0, edit.block.start) + newFragment + newXml.slice(edit.block.end);
  }
  zip.file(newSlidePath, newXml);

  // Register in [Content_Types].xml
  const contentTypesXml = await zip.file("[Content_Types].xml")?.async("string");
  if (contentTypesXml) {
    const override = `<Override PartName="/${newSlidePath}" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`;
    zip.file("[Content_Types].xml", contentTypesXml.replace("</Types>", `${override}</Types>`));
  }

  // Register relationship in presentation.xml.rels
  const presRelsPath = "ppt/_rels/presentation.xml.rels";
  const presRelsXml = await zip.file(presRelsPath)?.async("string");
  if (!presRelsXml) throw new Error("Не удалось прочитать presentation.xml.rels");
  const existingRIds = [...presRelsXml.matchAll(/Id="rId(\d+)"/g)].map((m) => Number(m[1]));
  const newRId = `rId${Math.max(0, ...existingRIds) + 1}`;
  const relEntry = `<Relationship Id="${newRId}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide${nextNum}.xml"/>`;
  zip.file(presRelsPath, presRelsXml.replace("</Relationships>", `${relEntry}</Relationships>`));

  // Insert into presentation.xml's sldIdLst at the desired position.
  const presXml = await zip.file("ppt/presentation.xml")?.async("string");
  if (!presXml) throw new Error("Не удалось прочитать presentation.xml");
  const existingIds = [...presXml.matchAll(/<p:sldId[^>]*id="(\d+)"/g)].map((m) => Number(m[1]));
  const newSlideId = Math.max(255, ...existingIds) + 1; // slide ids must be >= 256
  const newSldIdEl = `<p:sldId id="${newSlideId}" r:id="${newRId}"/>`;

  const sldIdEntries = [...presXml.matchAll(/<p:sldId[^>]*\/>/g)];
  let newPresXml: string;
  if (sldIdEntries.length === 0 || afterIndex >= sldIdEntries.length - 1) {
    // Append at the end of sldIdLst.
    newPresXml = presXml.replace("</p:sldIdLst>", `${newSldIdEl}</p:sldIdLst>`);
  } else {
    const insertAfterEl = sldIdEntries[afterIndex];
    const insertPos = insertAfterEl.index! + insertAfterEl[0].length;
    newPresXml = presXml.slice(0, insertPos) + newSldIdEl + presXml.slice(insertPos);
  }
  zip.file("ppt/presentation.xml", newPresXml);

  return zip.generateAsync({ type: "nodebuffer" });
}

export async function removeSlide(buffer: Buffer, index: number): Promise<Buffer> {
  const zip = await JSZip.loadAsync(buffer);
  const presXml = await zip.file("ppt/presentation.xml")?.async("string");
  if (!presXml) throw new Error("Не удалось прочитать presentation.xml");

  const sldIdEntries = [...presXml.matchAll(/<p:sldId[^>]*\/>/g)];
  const target = sldIdEntries[index];
  if (!target) throw new Error(`Слайд с индексом ${index} не существует`);

  const newPresXml = presXml.slice(0, target.index!) + presXml.slice(target.index! + target[0].length);
  zip.file("ppt/presentation.xml", newPresXml);
  // The slide's own XML/rels/content-type entry is left in the package unused
  // (orphaned parts are harmless and PowerPoint/LibreOffice ignore them) —
  // avoids having to also patch [Content_Types].xml and the rels file for a
  // simple MVP "remove from deck" action.
  return zip.generateAsync({ type: "nodebuffer" });
}

export async function reorderSlides(buffer: Buffer, fromIndex: number, toIndex: number): Promise<Buffer> {
  const zip = await JSZip.loadAsync(buffer);
  const presXml = await zip.file("ppt/presentation.xml")?.async("string");
  if (!presXml) throw new Error("Не удалось прочитать presentation.xml");

  const sldIdEntries = [...presXml.matchAll(/<p:sldId[^>]*\/>/g)];
  if (!sldIdEntries[fromIndex] || fromIndex === toIndex) {
    return buffer;
  }

  const elements = sldIdEntries.map((m) => m[0]);
  const [moved] = elements.splice(fromIndex, 1);
  elements.splice(Math.min(toIndex, elements.length), 0, moved);

  const listStart = presXml.indexOf("<p:sldIdLst");
  const listOpenEnd = presXml.indexOf(">", listStart) + 1;
  const listCloseStart = presXml.indexOf("</p:sldIdLst>");
  const newPresXml = presXml.slice(0, listOpenEnd) + elements.join("") + presXml.slice(listCloseStart);
  zip.file("ppt/presentation.xml", newPresXml);
  return zip.generateAsync({ type: "nodebuffer" });
}
